import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif, Roboto_Flex } from "next/font/google";

import "./globals.css";
import PrivvyProviderWrapper from "@/lib/providers/privyProvider";
import SolanaProviderWrapper from "@/lib/providers/solana-adapter-provider";


const geistMono = Roboto_Flex({
  style: "normal",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "1000",
  ],
  subsets: ["latin"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.style}  h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col"
      >
        <PrivvyProviderWrapper>
          <SolanaProviderWrapper>
            {children}
          </SolanaProviderWrapper>
        </PrivvyProviderWrapper>
      </body>
    </html>
  );
}